### ISSUE TITLE
Compatibility with LibWrapper

### ISSUE THREAD

**Issue by dirusulixes** [FLPub/symbaroum5ecore#15]
fvtt 9.255
symbaroum5ecore 1.0
midi-qol 0.9.35

Currently symbaroum5ecore and midi-qol are not compatible with multiple errors in console (sample below). It would be really nice, if possible, to have the choice to use both midi automations and the customisation to the DND5e system module needed to play Ruins of Symbaroum.

```
foundry.js:319 TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
[Detected 1 package: symbaroum5ecore]
    at Function.defineProperty (<anonymous>)
    at actor.js:70:14
    at Array.forEach (<anonymous>)
    at Function.patch (actor.js:59:29)
    at Function.register (actor.js:13:10)
    at core.js:66:8
    at Array.forEach (<anonymous>)
    at core.js:64:30
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5528:11)
    at Game._initializeGameView (foundry.js:6510:16)
    at Game._initializeView (foundry.js:6486:21)
    at Game.initialize (foundry.js:5433:16)
onError @ foundry.js:319
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
_call @ foundry.js:298
callAll @ foundry.js:253
setupGame @ foundry.js:5528
_initializeGameView @ foundry.js:6510
_initializeView @ foundry.js:6486
initialize @ foundry.js:5433
await in initialize (async)
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁libWrapperInit @ libWrapper-api.js:793
await in 🎁libWrapperInit (async)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:62611

foundry.js:319 TypeError: Cannot read properties of undefined (reading 'find')
[Detected 2 packages: symbaroum5ecore, system:dnd5e]
    at Actor5e.isSybActor (actor.js:313:43)
    at Actor5e.prepareBaseData (actor.js:103:14)
    at Actor5e.prepareData (foundry.js:10759:10)
    at Actor5e.prepareData (entity.js:57:11)
    at Actor5e._initialize (foundry.js:10558:12)
    at new Document (document.mjs:52:10)
    at new BaseActor (documents.mjs:62:1)
    at new <anonymous> (foundry.js:10531:5)
    at new Actor (foundry.js:13388:5)
    at new Actor5e (entity.js:14:16)
    at Actors._initialize (foundry.js:11447:15)
    at new WorldCollection (foundry.js:11433:10)
    at new Actors (foundry.js:11636:1)
    at Game.initializeDocuments (foundry.js:5587:30)
    at Game.setupGame (foundry.js:5535:10)
    at async Game._initializeGameView (foundry.js:6510:5)
```

**Comment by trioderegion** [comment]
It looks like this is an error on game startup?

If so I *may* be able to work around this libwrapper error, but midi is not likely to play nicely with symbaroum5e in general.

**Comment by dirusulixes** [comment]
yes, the error is on game startup. The module is not loaded and I cannot test incompatibilities further unfortunately.

**Comment by NashWise** [comment]
> It looks like this is an error on game startup?
> 
> If so I _may_ be able to work around this libwrapper error, but midi is not likely to play nicely with symbaroum5e in general.

Yup I can confirm that libwrapper is the main issue that comes out. Dynamic Active Effect also breaks down Symbaroum 5e module.

**Comment by trioderegion** [comment]
Could you all try the latest beta release? I may have resolved world loading issues in the presence of LibWrapper.

Manifest: https://github.com/FLPub/symbaroum5ecore/releases/download/1.0.-1/module.json

**Comment by dirusulixes** [comment]
I tested the release and the librwrapper shim solves the loading issues for me.
