### ISSUE TITLE
null _ID for flags.symbaroum5ecore.corruption update

### ISSUE THREAD

**Issue by dirusulixes** [FLPub/symbaroum5ecore#35]
I was trying to understand what is making some modules not work with symbaroum5ecore and I noticed this error with [Argon](https://github.com/theripper93/enhancedcombathud)  

```
Uncaught (in promise) Error: You must provide an _id for every object in the update data Array.
[Detected 2 packages: system:dnd5e, enhancedcombathud]
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:10185:32)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:10152:33)
    at ClientDatabaseBackend.update (backend.mjs:153:31)
    at async Function.updateDocuments (document.mjs:373:21)
    at async Item5e.update (document.mjs:456:21)
    at async Item5e.roll (entity.js:685:54)
    at async HTMLDivElement.<anonymous> (ExtendedCombatHud.js:643:11)
```

Digging a bit deeper I notice this update object that seemingly caused foundry to complain.

```
flags.symbaroum5ecore.corruption: {total: 0, expression: '0', summary: '0 (0)'}
_id: null
```

I'm not sure if I'm onto something that could be considered a bug or not.

**Comment by trioderegion** [comment]
What item are you rolling (if it is custom, could you attach it)? And is this occurring when rolling *through* Argon? or just with it enabled?

**Comment by trioderegion** [comment]
Mmm, it has to do with those "psuedo-items" it tries to roll. They have no ID when I try to cache their last rolled corruption. If I can easily work around it, I will try to slip it into the v10 update.
