### ISSUE TITLE
Resting menus fail in 1.0.5

### ISSUE THREAD

**Issue by dirusulixes** [FLPub/symbaroum5ecore#38]
fvtt 9.269
DND5e 1.6.2
symbaroum5ecore 1.0.5
no other modules loaded.

Clicking the rest buttons does nothing with the error thrown being:
```
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'flat')
    at Resting._getCorruptionRecovery (resting.js:65:46)
    at SybRestDialog.getData (syb-rest-dialog.js:88:34)
    at SybRestDialog._render (foundry.js:3062:29)
    at SybRestDialog.render (foundry.js:3021:10)
    at syb-rest-dialog.js:176:52
    at new Promise (<anonymous>)
    at SybRestDialog.restDialog (syb-rest-dialog.js:170:12)
    at Actor5e.shortRest (actor.js:169:29)
    at Actor5e.wrapper (shim.js:79:43)
    at Syb5eActorSheetCharacter._onShortRest (actor-sheet.js:377:27)
```

**Comment by dirusulixes** [comment]
is it just this the problem?https://github.com/FLPub/symbaroum5ecore/blob/3db2c9ecc3aadc25b2b618ff472cd9e946bf293d/scripts/modules/resting.js#L65

`const proficiency = actor.data.data.attributes.prof;` seems to work for me.

**Comment by trioderegion** [comment]
Thanks for the report ❤️ . I'll get this patched up!
