### ISSUE TITLE
After trying to add expertise to sheet through scoundrel drop down, i cant open character sheet again and get error

### ISSUE THREAD

**Issue by psdao1102** [FLPub/symbaroum5ecore#67]
Steps to reproduce:

Create a pc, add scoundrel to the sheet, click on scoundrel from sheet. pick up and drag expertise from table there into character sheet. close character sheet, attempt to reopen it.

error is as follows:

`Error: An error occurred while rendering Syb5eActorSheetCharacter 71. Cannot read properties of undefined (reading 'isSybActor')
    at Item5e.getChatData (item.js:79:19)
    at Item5e.wrapper (shim.js:79:43)
    at Syb5eActorSheetCharacter.getData (base-sheet.mjs:191:47)
    at Syb5eActorSheetCharacter.getData (character-sheet.mjs:23:33)
    at Syb5eActorSheetCharacter.getData (actor-sheet.js:321:35)
    at Syb5eActorSheetCharacter._render (foundry.js:5812:29)
    at Syb5eActorSheetCharacter._render (foundry.js:6532:17)
    at Syb5eActorSheetCharacter._render (actor-sheet.js:334:21)
    at Syb5eActorSheetCharacter.render (foundry.js:5769:10)
    at Syb5eActorSheetCharacter.render (foundry.js:7111:18)
o`

**Comment by psdao1102** [comment]
Sorry this is in the beta patch.

**Comment by trioderegion** [comment]
Closed by #70
